env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  eol-last: ["error", "never"]
  "no-multiple-empty-lines": [2, {"max": 99999, "maxEOF": 0}]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  linebreak-style: 0
